### ISSUE TITLE
Robot feet seem to stick to the floor

### ISSUE THREAD

**Issue by tobiaskunz** [dartsim/dart#10]
Robot can lean far forward without tipping over.

**Comment by mxgrey** [comment]
I haven't experienced or witnessed this behavior in a long time (although I do remember seeing it a couple years ago). Unless someone can offer a way to reproduce it with the latest DART, we might want to consider closing this issue.

**Comment by tobiaskunz** [comment]
I don't know if this problem still exists. If not, you can close this issue. I remember Hubo falling over without his feet ever moving.

**Comment by mxgrey** [comment]
Yep, I remember that too, but I think it was two years ago and in DART 2.0. I haven't noticed it on any simulated humanoid since then, although I have to admit that I haven't tried especially hard to recreate it.

**Comment by jslee02** [comment]
Let's close this issue since DART 2.0 is not supported and we have some humanoid examples working fine. Please reopen this issue if needed.
