### ISSUE TITLE
Adding a getMutexes() function to MetaSkeleton

### ISSUE THREAD

**Issue by brianhou** [dartsim/dart#1007]
In https://github.com/personalrobotics/aikido, we're currently opting to use `MetaSkeleton`s rather than `Skeleton`s. However, `MetaSkeleton`s don't have associated mutex(es) so I'm concerned we'll run into issues with thread safety.

It seemed like there was some discussion in #466 about what to do with `ReferentialSkeleton`s on that PR, but I don't think a `getMutexes()` method was ever added.

**Comment by mxgrey** [comment]
I edited the title for clarity. It wouldn't be helpful to add a mutex to `MetaSkeleton`, but a function like `getMutexes()` would be useful. The hard part is making sure that we have a good locking scheme for dealing with a set of mutexes instead of just a single mutex.

**Comment by jslee02** [comment]
@brianhou, @mxgrey, @mkoval, @gilwoolee I've create a WIP PR #1011 for this. Could you take a look at it when you guys have a chance? Thanks!

**Comment by jslee02** [comment]
Resolved by #1011
