### ISSUE TITLE
Pendulum tutorial text is out of sync with code.

### ISSUE THREAD

**Issue by xemjeff** [dartsim/dart#1049]
I just ran the Multi-Pendulum tutorial (on Ubuntu 16.04).
The text for the tutorial needs to be updated so that the tutorial edits to the code will compile.

**Lesson 1a, 1c**
The way shapes nodes are accessed has changed:
BodyNode::getVisualizationShape() is no longer used.

```
const ShapePtr& shape = bn->getVisualizationShape(j);
shape->setColor(dart::Color::Blue());
```
replace with :

```
auto visualShapeNodes = bn->getShapeNodesWith<VisualAspect>();
visualShapeNodes[j]->getVisualAspect()->setColor(dart::Color::Blue());
```

**Lesson 3:**
The pointer type for a BallJointConstraint has changed:

The declaration:

```
dart::constraint::BallJointConstraint* mBallConstraint;
```
should be:

```
dart::constraint::BallJointConstraintPtr mBallConstraint;
```

**Comment by jslee02** [comment]
I created #10 for this that only updates the pendulum tutorial, but I believe other tutorials might have the same issue.
