### ISSUE TITLE
Order of body nodes in Skeleton

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#105]
A. The Order of Body Nodes in Skeleton

DART assumes that the first body node in Skeleton::mBodyNodes is base body node and the list is ordered by breadth-first search ([BFS](http://en.wikipedia.org/wiki/Breadth-first_search)) or depth-first search ([DFS](http://en.wikipedia.org/wiki/Depth-first_search)) for the tree structure of the skeleton. This assumptions make the recursive dynamics algorithms to work properly.

DART however allows the user to decide the order by providing Skeleton::addBodyNode(). Here are possible problems:

P1. Adding body nodes in bad order
The recursive algorithms wouldn't work which is most critical problem.

P2. Multiple tree structures in one skeleton
The body node that doesn't have parent should be only base body node. The user is able to add multiple orphan body nodes. This means we are allowing multiple tree structures in one skeleton. The recursive algorithms would work but we may don't want this situation.

We can consider possible solutions as below:

S1. We don't change anything but the user should follow the role.

S2. Once all body nodes are added to the skeleton by the user, skeleton should re-order the list if the order is bad.
This option would solve (1) but not (2).

S3. We let the user specify just the root body node of a skeleton then the skeleton builds the list ordered by BFS or DFS. Skeleton::addBodyNode() will be removed and Skeleton::setRootBodyNode() will be added.
This option would solve (1) and (2). A tree structure of skeleton will be built by BFS or DFS because DART knows the root and parent/child relationship.

B. Concept of Tree Structure

So far, we assume that the user knows the concept of base body node and parent/child relationship in the tree structure. I think the concept is just for the dynamics algorithms. We can specify any link in a robot as a base body node, and the parent/child relationship will be determined by it.

Of course, we may expect that the user pick a link as a base body node and set the relationship properly, but some users may not want to or don't know how to. They just know (or want to provide) the list of links and the connectivity (without parent/child relationship) between two links by joints.

I'm not sure whether we should allow the user to build a robot without the concepts in DART so I'd like to listen to other's opinion about this issue, too.

**Comment by mxgrey** [comment]
I think this issue is closed with DART 5.0, for the following reasons:

(1) It's now impossible for BodyNodes to be added to a Skeleton out of order, because the parent of a new BodyNode must already be on the Skeleton before a new BodyNode can be added.

(2) If anyone wants to change the ordering of the BodyNodes, they can do so with the ``dart::dynamics::Group`` class which allows them to arrange and rearrange the indexing of BodyNodes in any way that they would like.
