### ISSUE TITLE
[Question] Is it possible to change constraint solver of dart::simulation::World?

### ISSUE THREAD

**Issue by EastskyKang** [dartsim/dart#1058]
Hello, 

I am trying to benchmark different constraint solver for various rigid body simulation scenarios. 

Can somebody give me some advice how to change default solver of dart world?

**Comment by jslee02** [comment]
DART currently supports two LCP solvers: Dantzig (identical to ODE's `dWorldStep()`) and [Projected Gauss-Seidel](https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method). Here is an example code for changing LCP solver:

```cpp
#include "dart/simulation/simulation.hpp"
#include "dart/constraint/constraint.hpp"

int main()
{
  auto world = dart::simulation::World::create();
  auto cs = world->getConstraintSolver();
  cs->setLCPSolver(dart::common::make_unique<dart::constraint::DantzigLCPSolver>(
      world->getTimeStep()));  // Default LCP solver
  cs->setLCPSolver(dart::common::make_unique<dart::constraint::PGSLCPSolver>(
      world->getTimeStep()));

  return 0;
}
```

**Comment by EastskyKang** [comment]
@jslee02 Thank you for your response.
