### ISSUE TITLE
3 memory leaks in mesh loading

### ISSUE THREAD

**Issue by Aneoshun** [dartsim/dart#1063]
### Bug Report
> Please answer the following questions for yourself before submitting an issue.
- [X] I checked the [documentation](http://dartsim.github.io/) and found no answer.
- [X] I checked to make sure that this issue has not already been filed.

#### Environment
* DART version: master 
* OS name and version name(or number): Ubuntu 16.04 
* compiler name and version number: GCC 5.4

Hi all, 

I have identified 3 leaks coming from the usage of Assimp's API. 

1) In the destructor of MeshShape, `delete mMesh;`  should be replaced by `aiReleaseImport(mMesh);` . The reason is that the memory associated to this mesh is stored and managed by the Importer used to create this mesh, aiReleaseImport will clean all this for you. See here http://assimp.sourceforge.net/lib_html/usage.html 
https://github.com/dartsim/dart/blob/36a6a48aeec4c4e586166c254011d1959ff9f27a/dart/dynamics/MeshShape.cpp#L148

2) The propertyStore instanciated here
https://github.com/dartsim/dart/blob/36a6a48aeec4c4e586166c254011d1959ff9f27a/dart/dynamics/MeshShape.cpp#L358
is never freed. I suggest to add `aiReleasePropertyStore(propertyStore);` at the end of the loadMesh function. 

3) The aiFile instanciated here
https://github.com/dartsim/dart/blob/36a6a48aeec4c4e586166c254011d1959ff9f27a/dart/dynamics/AssimpInputResourceAdaptor.cpp#L247
is not freed by the close protocol .
I have added `delete _file;` after this line 
https://github.com/dartsim/dart/blob/36a6a48aeec4c4e586166c254011d1959ff9f27a/dart/dynamics/AssimpInputResourceAdaptor.cpp#L261
and it solves my memory leaks issue.

After fixing these 3 leaks (plus one directly in Assimp https://github.com/assimp/assimp/issues/1934 ) I have no more memory leak according to valgrind. 
Let me know if you need more details. 

I hope this will help you.

**Comment by jslee02** [comment]
Appreciated for the detailed report. #1066 is created to fix the memory leaks.

**Comment by Aneoshun** [comment]
Thanks!
