### ISSUE TITLE
Voxel grid test fails against Octomap homebrew bottles

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#1078]

**Comment by yurivict** [comment]
It still links with ```liboctomath.so:math/octomap``` even though that configure says that the ```OctoMap``` version can't be used.

**Comment by jslee02** [comment]
It's very weird, but the test fails only with FCL installed by Homebrew. FCL installed from source works fine regardless of OS. All the FCL versions are 0.5.0.

**Comment by jslee02** [comment]
The voxel grid test passes with FCL installed with this command: `brew install fcl --build-from-source`. So the Homebrew formula is presumably fine but the bottles seem to cause the test failure, which is still odd.
