### ISSUE TITLE
Consider making friction and restitution properties belong to CollisionAspect instead of BodyNode

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#1179]
Currently coefficient of friction and coefficient of restitution are defined per BodyNode. I would propose defining them per geometric object by putting them into `CollisionAspect::Properties` instead of `BodyNode::Properties`. I think this may have been discussed before, but I can't find where that conversation may have happened.

This is somewhat related to #716.

**Comment by jslee02** [comment]
Now they are in `DynamicsAspect`, and the APIs in `BodyNode` are deprecated in #1369.
