### ISSUE TITLE
Implementing a Sensor In the Dart Physics engine

### ISSUE THREAD

**Issue by RomanBuckle** [dartsim/dart#1189]
Hi i am working on a project where i have to create an API to be able to create a model of a robot and add specific sensors to the robot such as a monocular camera and a 2D depth sensor or 1D depth sensor.
I have been looking about and have been unable to find anything on creating or implementing them.
It would be greatly appreciated if someone that knew more about this topic could shed some light on how to do this for me.

#### Environment
* DART version: 6.6.0 

Thanks Roman

**Comment by jslee02** [comment]
Thanks for raising this issue, and I also sensor simulation is a useful feature to have in DART. As mentioned in another [thread](https://github.com/dartsim/dart/issues/244), we're working on this and expect to continue on this after mid-December under our current schedule.

**Comment by jslee02** [comment]
Closing this issue as this duplicates #244. Let's continue on that thread!
