### ISSUE TITLE
doubts about installation dependency 

### ISSUE THREAD

**Issue by EngineerZhang** [dartsim/dart#1191]
Hi，I currently use this command `.\vcpkg.exe install ***`to install dependency,but the default plantform is x86,should I change the command to this`.\vcpkg.exe install ***:x64-windows`?Thanks a lot!

**Comment by jslee02** [comment]
Yes, if you want to build DART as x64 binary. As a note, you might want to use `--triplet` option to install multiple dependencies as a single line. Please refer to our [build script](https://github.com/dartsim/dart/blob/master/.appveyor.yml#L36-L58).
