### ISSUE TITLE
ros urdf to gazebo

### ISSUE THREAD

**Issue by gpldecha** [dartsim/dart#1202]
Hi,
I have managed to run dart with gazebo. I am interested in being able to set the restitution, damping and spring coefficients in a urdf.xaco . I seen there is a wiki on using dart with gazebo. It would be nice if there was urdf example on how to set all the physics properties.

**Comment by mxgrey** [comment]
URDF is not created or managed by DART; we simply support it as one option for loading robot simulations. You can find tutorials for writing URDFs [here](http://wiki.ros.org/urdf/Tutorials).

The recommended world+robot description format when using Gazebo is [SDF](http://sdformat.org/spec), although Gazebo does support URDF in some capacity.

If you find that Gazebo is not correctly setting restitution, damping, and spring coefficients when you use DART as the underlying physics engine, then that would be a Gazebo issue (not a DART issue), and it would be very helpful to report it on the [Gazebo issue tracker](https://bitbucket.org/osrf/gazebo/issues?status=new&status=open), especially if you can provide some code to recreate the problem.
