### ISSUE TITLE
libode-dev is required for build from source

### ISSUE THREAD

**Issue by eastskykang** [dartsim/dart#1203]
OS: Ubuntu 16.04 amd64
DART: release 6.6.2

I'm building dart release 6.6.2 version from source and it seems dart requires libode-dev library but it's omitted from installation manual: https://dartsim.github.io/install_dart_on_ubuntu.html

Is it deprecated in the latest version?

**Comment by mxgrey** [comment]
If I'm not mistaken, I think `libode-dev` should only be necessary for the optional library component `libdart-collision-ode`. The parts of ODE that DART has a hard dependency on should come with the source code in the folder `dart/external/odelcpsolver`.

Could you put your configuration and/or build errors in a [gist](https://gist.github.com/) and link them here?

**Comment by eastskykang** [comment]
@mxgrey  thank you for your response! 

Yes, I know that is optional. I just wanted to suggest add libode-dev to install guide, because it might be confusing to users.

**Comment by jslee02** [comment]
@eastskykang Thanks for the report. I added `libode-dev` to the installation instruction.

@mxgrey The installation guide was outdated, but it's now updated. :smile:
