### ISSUE TITLE
Add CI testing for Mojave once available

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#1213]
Let's keep an eye on these links:
* https://docs.travis-ci.com/user/reference/osx/#macos-version
* https://github.com/Microsoft/azure-pipelines-image-generation/issues/300

### Exit Criteria
- [x] Add Mojave test to Travis CI script
- [ ] Add or switch to Azure Pipelines

**Comment by scpeters** [comment]
the `xcode10.2` travis osx_image supports 10.14 mojave

**Comment by jslee02** [comment]
That's good news! :tada:

**Comment by scpeters** [comment]
fixed by #1269
