### ISSUE TITLE
Skeleton::State failing to capture joint states

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#1243]
This came to our attention in [this thread](https://github.com/dartsim/dart/issues/386#issuecomment-464606606). It's unclear to me what's causing this, since `Skeleton::State` has worked reliably for me in the past, but I've confirmed that it's currently not working, and I'm investigating why.

**Comment by mxgrey** [comment]
I'll be adding a regression test for this to make sure the issue doesn't recur.

**Comment by jslee02** [comment]
Resolved by #1245
