### ISSUE TITLE
CMake: cannot find octomap lib

### ISSUE THREAD

**Issue by costashatz** [dartsim/dart#1252]
#### Environment
* DART master, 6.8.0 (but the same applies to release-6.7)
* Ubuntu 18.04 and Arch Linux

When trying to compile the latest DART (master or release-6.7) without octomap installed in my computer, I get the following:

```sh
/usr/bin/ld: cannot find -loctomap
collect2: error: ld returned 1 exit status
make[2]: *** [dart/CMakeFiles/dart.dir/build.make:2116: lib/libdart.so.6.8.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:355: dart/CMakeFiles/dart.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

It makes sense, because this line in [dart/CMakeLists.txt](https://github.com/dartsim/dart/blob/master/dart/CMakeLists.txt#L138) tries to link to `octomap` and of course if it is not installed it cannot link to it.

Is this a known issue or am I missing something?

**Comment by jslee02** [comment]
It's an obvious bug. It should be included only when octomap target is imprted. Let me fix this tonight.
