### ISSUE TITLE
Loading a world with a robot in it

### ISSUE THREAD

**Issue by AranBSmith** [dartsim/dart#1361]
Hi, simple question here. 

I am working on a project that stabilizes a robot in a world before running a simulation. But I would like to avoid this step as I will be running the simulation many times, if I can stabilize the robot once, and save that world with the stabilized robot in it, then load that saved world with the stabilized robot, what would be the best way of doing it? What are the best classes for this task?

**Comment by acxz** [comment]
@AranBSmith It is more appropriate to ask this question on the [Forums](https://dartsim.discourse.group/) than on the github. The forum is for implementation help while the github issue tracker is for development related issues.
