### ISSUE TITLE
Setting DataVariance=DYNAMIC causes simulation to slow and then stop

### ISSUE THREAD

**Issue by farg967** [dartsim/dart#1380]
A explained in the forum [here](https://dartsim.discourse.group/t/setting-datavariance-dynamic-causes-simulation-to-slow-and-then-stop/95/3). Setting dataVariance to DYNAMIC or DYNAMIC_ELEMENTS causes the simulation to slow and then stop after approximately 10 seconds.

In the forum Grey explains the problem as..

It seems that [this line](https://github.com/dartsim/dart/blob/d8f2636cc3d36430b5de65405b0b13c136485f94/dart/gui/osg/render/LineSegmentShapeNode.cpp#L221) is likely the culprit, because it’s adding a primitive set without removing the previous one. So the set of line segments that need to be drawn get piled up on top of each other instead of having the new set replace the old set.

**Comment by jslee02** [comment]
This issue should be resolved by https://github.com/dartsim/dart/pull/1381. Please let me know if this doesn't work for you.
