### ISSUE TITLE
当android studio运行或者断点flutter程序的时候Dart.exe程序内存异常

### ISSUE THREAD

**Issue by deleteNames** [dartsim/dart#1467]
电脑环境为：windows7 sp1
android studio版本为：3.6.3
Dart版本为：2.8.1
Flutter版本为：1.17.0
当电脑运行应用程序为：Gradle task 'assembleDebug'...的时候内存开始增加，有一定几率运行正常，但是大概率运行内存爆满
希望大牛帮忙看看，解决这个bug

**Comment by jslee02** [comment]
Closing as this issue seems about the Dart programming language. Feel free to reopen if that's not the case.
