### ISSUE TITLE
Malformed .pc pkg-config file generated by DART

### ISSUE THREAD

**Issue by traversaro** [dartsim/dart#1496]
I happen to look into the `.pc` pkg-config file generated by DART, and I noticed something strange in the `Requires` field:
~~~
prefix=${pcfiledir}/../..
# This file was generated by CMake for dart
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include/dart

Name: dart
Description: Dynamic Animation and Robotics Toolkit.
Version: 6.9.4
Requires: eigen, ccd, fcl, assimp, boost
Libs: -L${libdir} -ldart
Cflags:  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /permissive- /Zc:twoPhase-
~~~

In particular, all the field in `Requires` should be valid pkg-config installed packages, but I found the following problems: 
* `eigen` is not the pkg-config name for the Eigen3 library, that is instead `eigen3` 
* `boost` does not identify any pkg-config  file, as at the best of my knowledge `boost` does not ship `.pc` pkg-config file on any distro. To see that, on Ubuntu 20.04 install  the `libboost-all-dev` and then execute `pkg-config --list-all | grep boost`

### Bug Report
- [x] I checked the [documentation](http://dartsim.github.io/) and the [forum](https://dartsim.discourse.group/) but found no answer.
- [x] I checked to make sure that this issue has not already been filed.

#### Environment
> Select the following information.
* DART version: [e.g., master, 6.8.3] master
* OS name and version name(or number): Ubuntu 20.04
* Compiler name and version number: not relevant

#### Expected Behavior
I would expect the `.pc` pkg-config file installed by dart to be well formed. 

#### Current Behavior
The one described at the top of the issue. 

#### Steps to Reproduce
> Please provide detailed steps for reproducing the issue.
1. Install dart and inspect the installed `lib/pkgconfig/dart.pc`  file

**Comment by jslee02** [comment]
Thank you for the suggestions! Fixed in #1594
