### ISSUE TITLE
ipopt include folder changed recently

### ISSUE THREAD

**Issue by Moisan** [dartsim/dart#1504]
### Bug Report
- [x] I checked the [documentation](http://dartsim.github.io/) and the [forum](https://dartsim.discourse.group/) but found no answer.
- [x] I checked to make sure that this issue has not already been filed.

#### Environment
* DART version: 6.9.4
* OS name and version name(or number): macOS Catalina
* Compiler name and version number: Clang 3.9.1

#### Expected Behavior
dartsim should be able to compile with the latest ipopt version (currently 3.13.2).

#### Current Behavior
```
/tmp/dartsim-20200921-64782-nd7k16/dart-6.9.4/dart/optimizer/ipopt/IpoptSolver.hpp:36:10: fatal error: 'coin/IpTNLP.hpp' file not found
#include <coin/IpTNLP.hpp>
         ^~~~~~~~~~~~~~~~~
```

#### Steps to Reproduce
1. install ipopt 3.13.2
2. build dartsim 6.9.4 with this version of ipopt

I believe the issue is coming from a change of directory for the include files from ipopt between version 3.12 and 3.13. To fix this issue, one can change the include line to `#include <IpTNLP.hpp>`. However this would make dartsim not backward-compatible with previous versions of ipopt.

Note that there is another problematic include in `optimizer/ipopt/IpoptSolver.hpp` that will also need to be changed: `#include <coin/IpIpoptApplication.hpp>`.

**Comment by jslee02** [comment]
Thanks for the report! This should be fixed by #1506
