### ISSUE TITLE
Grasping: DART very slow on contact between end-effector and object

### ISSUE THREAD

**Issue by vincentmaye** [dartsim/dart#1532]
Hi,
first of all, great engine! I can finally simualte my model without the unrealistic behaviour occuring with other solvers like ODE.
Currently, I am trying to simulate grasping between a robotic hand and a 3D mesh in Gazebo. When contact is established between the fingers and the object surface the simulation-to-real time drops from 1.0 to 0.01. Upon checking the show contacts GUI-feature from Gazebo it appears like hundreds of contacts are being evaluated, which I guess to be the source of this rapid slow-down. Am I correct here?
Furthermore, how could I limit the amount of contacts to evaluate, since changing the max_contacts tag in the SDF files does not have an effect! Or is there anything else I can do to resolve this?
Thanks!

**Comment by mxgrey** [comment]
When it comes to simulations that involve grasps there tend to be two very different use-cases:

1. The physical simulation of the grasp behavior is a very important output for the researcher who is running the simulation. Maybe the researcher wants to verify that a certain grasping strategy is feasible or reliable.

2. The exact grasp behavior is not very important to the overall output of the simulation, as long as the grasp occurs and the robot reliably holds onto the object.

If you're in situation (1) your choices are:

1a. Carefully tune everything about your simulation to get the best trade-off between speed and accuracy that you can. This tends to be very painstaking.

1b. Use a more specialized simulator that's aimed at simulating grasps. Those more specialized simulators usually cannot account for articulated rigid body dynamics.

If you're in situation (2), then I recommend using a plugin that creates a fake joint between the object and the grasper once some conditions of "grasping" have been met. You'll also want to use collision bitmasks to completely filter away collisions between the grasper and the object that will be grasped. You can find various examples of plugins that [create](https://github.com/osrf/gazebo/blob/0d1642979382d95ae5a120fdccaeb7ad4c51cf36/plugins/HarnessPlugin.cc#L268) and [remove](https://github.com/osrf/gazebo/blob/0d1642979382d95ae5a120fdccaeb7ad4c51cf36/plugins/HarnessPlugin.cc#L433) such a joint.
