### ISSUE TITLE
Quick question about APIs

### ISSUE THREAD

**Issue by junhyeokahn** [dartsim/dart#1533]
Hello!
First of all, thanks for all your efforts in maintaining this nice repo.

I have a couple of questions on the APIs in ```skeleton``` class.
I see two different Jacobian derivative functions which are ```getJacobianSpatialDeriv``` and ```getJacobianClassicDeriv```.
What is the difference or the relationship between these two?

**Comment by mxgrey** [comment]
The `getJacobianSpatialDeriv` gives the time-derivative of the Jacobian according to [spatial vector algebra](https://homes.cs.washington.edu/~todorov//courses/amath533/FeatherstoneSlides.pdf), whereas the `getJacobianClassicDeriv` gives the time-derivative of the Jacobian according to classic vector algebra.

If you're not familiar with the difference, you almost certainly want the `getJacobianClassicDeriv`.
