### ISSUE TITLE
CONTRIBUTING.md out of date

### ISSUE THREAD

**Issue by peci1** [dartsim/dart#1549]
### Bug Report
> Please answer the following questions for yourself before reporting a bug.
- [x] I checked the [documentation](http://dartsim.github.io/) and the [forum](https://dartsim.discourse.group/) but found no answer.
- [x] I checked to make sure that this issue has not already been filed.

#### Environment
> Select the following information.
* DART version: OSRF 6.10
* OS name and version name(or number): Ubuntu 18.04
* Compiler name and version number: GCC 8.4.0

I was looking in the CONTRIBUTING.md guide and it seems to be out of date. It suggests that header files should go in `include/` subdirectory and source files into `src/` subdirectory. However, this pattern is apparently not applied in the DART source code.

**Comment by jslee02** [comment]
Good catch! This should be fixed by https://github.com/dartsim/dart/pull/1551
