### ISSUE TITLE
Empty skeleton cause segfault

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#157]
A skeleton that contains zero body node causes segfault in [Skeleton::int()](https://github.com/dartsim/dart/blob/master/dart/dynamics/Skeleton.cpp#L133).

**Comment by mxgrey** [comment]
It's probably worth noting that Skeleton::init() is essentially deprecated. Once we've completely removed the public constructors for BodyNodes and Joints, there will no longer be a purpose for Skeleton::init().

**Comment by mxgrey** [comment]
Skeleton::init() is officially gone from the API, so this issue can be closed.
