### ISSUE TITLE
Keep branch release-6.3 alive

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#1578]
I just wanted to leave a note that we need to keep the `release-6.3` branch alive because the [ROS Kinetic distribution](https://github.com/ros/rosdistro/issues/26853) is relying on it. I tried to [redirect the distribution](https://github.com/ros/rosdistro/pull/29279) to use tag `v6.3.1`, but tags are not allowed for the reasons mentioned [here](https://github.com/ros/rosdistro/pull/20286/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055).

I've recreated the branch off of the `v6.3.1` tag. We don't have to do any further development on this branch, but we just need to keep it alive until Kinetic is retired.

@jslee02 feel free to close this issue once you've seen it. No action is needed, I just wanted to make sure you're aware of why that branch is back from the dead.

**Comment by jslee02** [comment]
Thanks for having me informed! I just updated the repository settings to protect the release branches from being deleted just in case.
