### ISSUE TITLE
Single Soft Body for Full Articulated Skeleton

### ISSUE THREAD

**Issue by lakshmipathyarjun6** [dartsim/dart#1589]
From the tutorials and this paper: https://www.cc.gatech.edu/graphics/projects/Sumit/homepage/papers/sigasia11/jain_softcontacts_siga11.pdf, my understanding is that soft bodies can only be added to a single body node.

Is it instead possible to embed a full articulated system within a single soft body similar to http://graphics.cs.cmu.edu/projects/fastsimuldbody/fastsimuldbody.pdf + do skeleton driven simulation of said body?

**Comment by jslee02** [comment]
Yes, the current implementation is based on the first paper, but the second model is currently not supported.
