### ISSUE TITLE
ImportError: cannot import name ‘pydart2_api’ from partially initialized module ‘pydart2’ on Ubuntu

### ISSUE THREAD

**Issue by cpacchierotti** [dartsim/dart#1595]
#### Environment
* DART version: 6.9.0
* OS name and version name(or number): Ubuntu 20.04
* Compiler name and version number: GCC 9.4.0 / Python 3.8.10

I followed the [installation guide](https://pydart2.readthedocs.io/en/latest/install.html#install-using-cmake-old-style), both the "Install with pip (easy)" and "Install from source code"

In both cases, when I try to do
```
$ python3
>>> import pydart2 as pydart
```
I end up with the following error
```
import pydart2 as pydart
Traceback (most recent call last):
File “”, line 1, in
File “/usr/local/lib/python3.8/dist-packages/pydart2/init.py”, line 5, in
from . import pydart2_api as papi
ImportError: cannot import name ‘pydart2_api’ from partially initialized module ‘pydart2’ (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/pydart2/init.py)
```

Thank you.

**Comment by jslee02** [comment]
[pydart2](https://github.com/sehoonha/pydart2) was the first Python binding for DART as an external package, but it's no longer supported as far as I know. Please consider using dartpy instead, which is the built-in Python binding. Here is the installation guide: http://dartsim.github.io/install_dartpy_on_ubuntu.html.
