### ISSUE TITLE
Default Inertia mass equal to 1kg

### ISSUE THREAD

**Issue by costashatz** [dartsim/dart#1604]
This is not exactly a bug (nor a feature request).

### Bug Report

- [x] I checked the [documentation](http://dartsim.github.io/) and the [forum](https://dartsim.discourse.group/) but found no answer.
- [x] I checked to make sure that this issue has not already been filed.

#### Environment

* DART version: master (6.11, 6.10, and I guess most others)
* OS name and version name(or number): does not matter
* Compiler name and version number: does not matter

#### Expected Behavior
When reading URDF, there are a few links that do not define inertia properties. The current default behavior of DART is to assume a mass of 1kg and identity moment of inertia (see [here](https://github.com/dartsim/dart/blob/main/dart/dynamics/Inertia.hpp#L68-L71)). The issue with this is that in big URDFs that we do not make (e.g., Talos humanoid) there can be several hidden links like this and then the simulation behaves weirdly (this is because usually these links are "dummy" links to create some complex structure or for creating frames). Right now I have to check all URDFs and clean them from all these links.

I suggest giving either `Inertia` a different default initialization or changing the URDF parser to include a "dummy" inertia when there is no inertia tag: what I usually do is put put small mass (1e-8) and the moments of inertia to identity*mass. This gives normal behavior.

#### Steps to Reproduce
1.  Take any URDF with a link with no inertia tag
2.  Load it in DART
3.  Observe the simulation
4.  Or print the mass/moment of inertia

**Comment by jslee02** [comment]
How about we let the user decides which values to use for the missing properties? Changing the default values could still be a problem for other usesr (e.g., someone could consider 1e-8 is still too large or too small value). #1605 is a tentative solution to this.

**Comment by costashatz** [comment]
This is very good. Thanks a lot. If you can merge this also in version 6.11.1+ I'd appreciate it (I haven't still restructured my code for DART master v7+).

**Comment by jslee02** [comment]
I'm thinking of merging this to 6.12.0, which is the current `main` branch. DART v7 is in `dart7/*` branches. Would this work for you?

**Comment by costashatz** [comment]
I guess so.. I remember the `main` to be for DART 7, but I guess you changed this. So 6.12.0 (assuming that the API is the same as 6.11.x) would be fine for me.

**Comment by jslee02** [comment]
Great. Yeah, it's changed because it would take some time for DART 7 to be ready for release. I thought it'd be good to keep DART 6 as the mainstream (so in `main`) until then. Sorry for any confusion!

**Comment by costashatz** [comment]
No worries. If you can update the issue when the PR is merged. Thanks a lot!
