### ISSUE TITLE
module 'dartpy.gui.osg' has no attribute 'InteractiveFrame'

### ISSUE THREAD

**Issue by lisheng-k** [dartsim/dart#1606]
Hi, 

sorry, I have to raise an issue here. I got an error when using the 'dart.gui.osg.InteractiveFrame', there are more chances to get a reply from this channel.

The error is that: 
when running the 'drag and drop' example 'python/examples/drag_and_drop/main.py' the error comes:
"
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    main()
  File "main.py", line 11, in main
    frame = dart.gui.osg.InteractiveFrame(
AttributeError: module 'dartpy.gui.osg' has no attribute 'InteractiveFrame'
"
does anyone have a clue about how to fix it?

The code version is : the version is : HEAD, tag: v6.9.0

I also have another error -- AttributeError: module 'dartpy.gui.osg' has no attribute 'GUIEventHandler'

looks like it's about the installtion. 

thank you in advance.

**Comment by jslee02** [comment]
I believe this can be resolved by [this comment](https://github.com/dartsim/dart/issues/1602#issuecomment-923062137) as well. Feel free to reopen if it's not the case.
