### ISSUE TITLE
Brew dartsim dependency installation issue

### ISSUE THREAD

**Issue by shbang91** [dartsim/dart#1614]
> If you're not reporting a bug, please use the [forum](https://dartsim.discourse.group/) to ask questions.

### Bug Report
> Please answer the following questions for yourself before reporting a bug.
- [o] I checked the [documentation](http://dartsim.github.io/) and the [forum](https://dartsim.discourse.group/) but found no answer.
- [o] I checked to make sure that this issue has not already been filed.

#### Environment
> Select the following information.
* DART version: 6.11
* OS name and version name(or number): macOS BigSur 11.6
* Compiler name and version number: gcc 4.2.1

#### Current Behavior
 When I try to install dart dependencies by commanding `brew install dartsim --only-dependencies`, some of the dependencies left in unlinked keys in my Cellar(from `brew doctor`):
```
> Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  assimp
  nlopt
  boost
  harfbuzz
  zstd
  bullet
  tinyxml2
  fcl
  sdl2
```

> Such unlinked dependencies cause error to show up when invoking `cmake ..`:
```
--
-- ============================================
--                 DART 6.11.1
-- ============================================
CMake Error at /usr/local/Cellar/cmake/3.21.3_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find fcl (missing: FCL_INCLUDE_DIRS FCL_LIBRARIES) (Required is
  at least version "0.3.2")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.21.3_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findfcl.cmake:56 (find_package_handle_standard_args)
  cmake/DARTFindfcl.cmake:9 (find_package)
  cmake/DARTMacros.cmake:81 (include)
  cmake/DARTFindDependencies.cmake:21 (dart_find_package)
  CMakeLists.txt:158 (include)
```

> For the case of fcl, here are the directories that fcl reside in my machine:
```
./local/opt/fcl
./local/Cellar/fcl
./local/Cellar/fcl/0.7.0/include/fcl
./local/Cellar/fcl/0.7.0/lib/cmake/fcl
./local/Cellar/fcl/0.7.0/share/fcl
```

**Comment by shbang91** [comment]
Thanks to your suggestion, after I` sudo chown $(whoami) /usr/local/lib/cmake` and manually `brew link`each dependencies, I could finally succeed to compile. However,  when I tried to run the `atlas_simbicon` example, it just gave me an error message:` Illegal instruction: 4`. I suspect two sources contributing to such error.

The first one is the` cmake ..` output:
```
CMake Warning at cmake/DARTMacros.cmake:145 (message):
  Looking for pagmo - NOT found, to use dart-optimizer-pagmo, please install
  pagmo
Call Stack (most recent call first):
  dart/optimizer/pagmo/CMakeLists.txt:3 (dart_check_optional_package)


-- Could NOT find ODE (missing: ODE_DIR)
-- Performing Test BT_USE_DOUBLE_PRECISION
-- Performing Test BT_USE_DOUBLE_PRECISION - Failed
CMake Warning at cmake/DARTMacros.cmake:145 (message):
  Looking for lz4 - NOT found, to use dart-planning, please install lz4
Call Stack (most recent call first):
  dart/planning/CMakeLists.txt:8 (dart_check_optional_package)
```
The second one is the warning messages during compiling:
```
ld: warning: dylib (/usr/local/lib/libccd.2.0.dylib) was built for newer macOS version (11.0) than being linked (10.8)
ld: warning: dylib (/usr/local/Cellar/fcl/0.7.0/lib/libfcl.dylib) was built for newer macOS version (11.0) than being linked (10.8)
ld: warning: dylib (/usr/local/lib/libboost_system-mt.dylib) was built for newer macOS version (11.0) than being linked (10.8)
ld: warning: dylib (/usr/local/lib/libboost_filesystem-mt.dylib) was built for newer macOS version (11.0) than being linked (10.8)
ld: warning: dylib (/usr/local/lib/liboctomap.1.9.7.dylib) was built for newer macOS version (11.0) than being linked (10.8)
ld: warning: dylib (/usr/local/Cellar/assimp/5.0.1/lib/libassimp.dylib) was built for newer macOS version (11.0) than being linked (10.8)
ld: warning: dylib (/usr/local/lib/liboctomath.1.9.7.dylib) was built for newer macOS version (11.0) than being linked (10.8)
ld: warning: dylib (/usr/local/Cellar/ipopt/3.14.4/lib/libipopt.dylib) was built for newer macOS version (11.0) than being linked (10.8)
```

I would really appreciate any suggestion from you.

**Comment by jslee02** [comment]
Yeah, this is a known issue. You need to install the head of OpenSceneGraph by running `brew install openscenegraph --HEAD` and then rebuild DART. Please see https://github.com/dartsim/dart/issues/1439 for the details.
