### ISSUE TITLE
Does dartpy support closed loop(parallel) structure/mechanism?

### ISSUE THREAD

**Issue by lisheng-k** [dartsim/dart#1618]
Hi, 

I have to raise an issue here. it's about closed-loop (parallel) structure in dartpy.

I descrived a parallel structure (a delta robot) in sdf file, then tried to parser the file with dartpy.

but the error came out and said :
"
Error [SdfParser.cpp:1138] [SdfParser::readAllJoints] Joint named [rear2_platform] is claiming Link [platform] as its child, but that is already claimed by Joint [rear1_platform]. Joint [rear2_platform] will be discarded
Error [SdfParser.cpp:1138] [SdfParser::readAllJoints] Joint named [rear3_platform] is claiming Link [platform] as its child, but that is already claimed by Joint [rear1_platform]. Joint [rear3_platform] will be discarded
"

looks like a link can only be one 'child' to one 'parent' link.

Is there a specific way to connect a child link to more than one parent link?

or, does dartpy support this kind of structure.

The structure I described in the sdf is -- a mobile platform linked to three separate links with three ball joints.

image see bellow:

![Screenshot from 2021-11-01 14-17-24](https://user-images.githubusercontent.com/34022140/139677770-93f24f9d-d4ec-47ac-b4b0-a151f1e0b915.png)

![Screenshot from 2021-11-01 14-18-18](https://user-images.githubusercontent.com/34022140/139677943-79e3eb4e-b946-4230-af1b-683ab6313354.png)

I checked the dart code., found here 
"JointMap readAllJoints"

![Screenshot from 2021-11-01 14-39-51](https://user-images.githubusercontent.com/34022140/139680784-813fc017-414d-4eea-8c4a-306cfffa2f06.png)

thanks in advance !

**Comment by jslee02** [comment]
DART supports closed loop structure, but the current SDF parser doesn't. You could form a closed loop structure by adding dynamic joint constrains in code. Here is an example: https://github.com/dartsim/dart/blob/b663c87e73e3c48295a856f22d5f455be9dc3443/python/examples/rigid_loop/main.py

**Comment by lisheng-k** [comment]
> DART supports closed loop structure, but the current SDF parser doesn't. You could form a closed loop structure by adding dynamic joint constrains in code. Here is an example: https://github.com/dartsim/dart/blob/b663c87e73e3c48295a856f22d5f455be9dc3443/python/examples/rigid_loop/main.py

great thanks, 
I will try that !
