### ISSUE TITLE
Install error when "sudo apt-add-repository ppa:dartsim/ppa"

### ISSUE THREAD

**Issue by ANABUR920** [dartsim/dart#1656]
> If you're not reporting a bug, please use the [forum](https://dartsim.discourse.group/) to ask questions.

### Bug Report
> Please answer the following questions for yourself before reporting a bug.
- [x] I checked the [documentation](http://dartsim.github.io/) and the [forum](https://dartsim.discourse.group/) but found no answer.
- [ ] I checked to make sure that this issue has not already been filed.

#### Environment
> Select the following information.
* DART version: DART 6.8
* OS name and version name(or number):  Ubuntu 18.04, 
* Compiler name and version number: [gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008, NVCC 10.2, clang version 8.0.1-3build1, python=3.8]

#### Expected Behavior
command : sudo apt-add-repository ppa:dartsim/ppa

bug:

Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 12, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 67, in <module>
    from gi.repository import Gio
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'

**Comment by jslee02** [comment]
It seems not a dartsim/ppa specific error. Could you please retry adding the dartsim PPA? Please reopen if this issue still persistent.
