### ISSUE TITLE
repo size is so huge, please rebase a smaller one

### ISSUE THREAD

**Issue by jinfagang** [dartsim/dart#1659]
![image](https://user-images.githubusercontent.com/21303438/165013596-ad24a57a-7c14-4d46-954d-326056315af5.png)

IDK why a c++ lib can have so huge size..

**Comment by jslee02** [comment]
I believe the actual size of the codebase is about 57.2 MB. The additional size comes from the Git history, stored in `.git` directory. If you want to download without the full history, you could do a [shallow clone](https://git-scm.com/docs/git-clone) with `--depth 1` (e.g., `git clone git@github.com:dartsim/dart.git 7.0 --depth 1`), which is about 72.9 MB.
