### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by jinfagang** [dartsim/dart#1660]
```
optimizer/nlopt/NloptSolver.cpp:240:1: error: ‘nlopt’ does not name a type; did you mean ‘float’?
 nlopt::algorithm NloptSolver::getAlgorithm() const

```

**Comment by jslee02** [comment]
Please provide more details on how to reproduce this error. Ideally report following [`bug_report.md`](https://github.com/dartsim/dart/blob/87c0e30aad0a5706d53bbd8e1146333c5cd37786/.github/ISSUE_TEMPLATE/bug_report.md) template, which is automatically created when you click the "New issue" button.
