### ISSUE TITLE
Contact model documentation

### ISSUE THREAD

**Issue by Timothee-ANNE** [dartsim/dart#1662]
Hello,

I'm using DART for an experiment relying on contacts between a robot and the environment. 
Is there some documentation or reference about the theoretical contact model used in DART ?
(I didn't found anything more than the contact constraint code: https://github.com/dartsim/dart/blob/main/dart/constraint/ContactConstraint.cpp) 

Thanks.

**Comment by jslee02** [comment]
It's not up-to-date, but currently the best doc would be this [note](https://github.com/dartsim/dart/blob/87c0e30aad0a5706d53bbd8e1146333c5cd37786/docs/lcp.pdf). Feel free to reach out to me for more details.
