### ISSUE TITLE
Setting friction coeff in setRestitutionCoeff function

### ISSUE THREAD

**Issue by shpark1359** [dartsim/dart#1676]
https://github.com/dartsim/dart/blob/798e6f521e100245d0cc5ff922963f8902676f57/dart/dynamics/BodyNode.cpp#L701

In the BodyNode::setRestitutionCoeff, it calls setFrictionCoeff of DynamicsAspects of its ShapeNodes.

**Comment by jslee02** [comment]
Thanks for catching this out! #1677
