### ISSUE TITLE
How stable will be API with new versions?

### ISSUE THREAD

**Issue by olzhas** [dartsim/dart#1679]
Hello!

I was thinking to start experimenting with adding VulkanSceneGraph (https://vsg-dev.github.io/VulkanSceneGraph/) to dartsim.
I was wondering that if I start with DART6, will I have to change the code a lot with newer versions released?

Thank you!

**Comment by jslee02** [comment]
The current policy is keeping the API backward compatibility within the same major version, and so does DART 6. However, DART 7 and 8 could introduce significant API changes.
