### ISSUE TITLE
Applying 3 different external forces to skeleton and visualize them

### ISSUE THREAD

**Issue by omerkayan** [dartsim/dart#1730]
Hi all,

As you can see in the picture, I want to apply 3 different external forces to the specific points of my skeleton and I want to visualize them via arrow shapes. I am quite new to dartsim. I found something about addExtForce() and addExtTorque(). But I could not do anything. Could you please someone help me?

![image](https://user-images.githubusercontent.com/81143460/211052978-a1c97b74-1093-4545-9357-0b4c9e649fd2.png)

**Comment by jslee02** [comment]
Yes, the [`addExtForce()`](https://dartsim.github.io/dart/v6.13.0/d5/d2e/classdart_1_1dynamics_1_1BodyNode.html#a4332e12156d1845039b89b05eb0c136e) method in DART can be used to apply an external force to a body. This method allows you to specify the force vector and the point of application using optional parameters, such as an offset from the origin of the body's reference frame, and whether the force and offset are in local or global coordinates. You can refer to the DART API documentation and [example code](https://github.com/dartsim/dart/blob/main/examples/tinkertoy/TinkertoyWorldNode.hpp#L132) for more details on how to use this method.
