### ISSUE TITLE
DoF name

### ISSUE THREAD

**Issue by YunfeiBai** [dartsim/dart#178]
It would be better to be able to define name for each DoF in skel file. When loading the skel file, assign the name to each DoF. And can access the DoF directly by name.

**Comment by jslee02** [comment]
By #288, we have a place to define name for each DoF. The remain things to do is (a) defining tag for dof name in skel file and (b) making the skel parser can parse it.

**Comment by jslee02** [comment]
This feature is implemented by #288.
