### ISSUE TITLE
Missing parentheses in config.hpp

### ISSUE THREAD

**Issue by costashatz** [dartsim/dart#1837]
There are a few parentheses missing in the macro definitions in config.hpp that make the compilation of examples relying on them to fail.

In short:

- https://github.com/dartsim/dart/blob/v6.14.4/dart/config.hpp.in#L28 we need one more parenthesis at the end
- https://github.com/dartsim/dart/blob/v6.14.4/dart/config.hpp.in#L34 we need one more parenthesis at the end

Thank you in advance!

**Comment by jslee02** [comment]
Good catch. Fixed by #1838. Thank you!
