### ISSUE TITLE
MeshShape::setScale does not accept negative values?

### ISSUE THREAD

**Issue by costashatz** [dartsim/dart#1839]
I do not understand why `MeshShape::setScale()` [does not accept negative values](https://github.com/dartsim/dart/blob/main/dart/dynamics/MeshShape.cpp#L239). This is a common practice to mirror the mesh (otherwise we need to have multiple "duplicate" meshes, especially when using the URDF format).

Also, this check was "recently" added (I did not check when this happened, but it wasn't there for many years that I am using the library). Is there a specific rationale/guideline for this? Imho, we should allow negative scaling.

**Comment by jslee02** [comment]
Accepting negative values makes sense to me. We may need to ensure that it works fine with the codebase (e.g., [updating bounding box](https://github.com/dartsim/dart/blob/cac87c136070a374b4705983c5a3a29db544d0e2/dart/dynamics/MeshShape.cpp#L358-L361)) and Assimp also allows it.

Regarding when and why it was changed, I don't recall quite frankly. The git log says that line was changed 6 years ago (from checking individual xyz components to using Eigen's all() function) and the previous commit of the 6 years ago also didn't accept negative values.

<img width="750" alt="image" src="https://github.com/user-attachments/assets/65045ca8-c7a2-4180-8de8-36581fad20df">

<img width="971" alt="image" src="https://github.com/user-attachments/assets/0db9b15b-2faa-40ff-bc16-72aee971b6c9">

**Comment by costashatz** [comment]
Oh I see what happened. I was compiling with disabled assertions!

In any case, we should allow for negative scaling. Apart from the `bounding box update`, where else should we handle this?

**Comment by jslee02** [comment]
It seems only the updating bounding box. #1841 to continue this discussion!

**Comment by jslee02** [comment]
Closing per #1841. Please let me know if this works for you!
