### ISSUE TITLE
Adding color member in Marker class?

### ISSUE THREAD

**Issue by Sosi** [dartsim/dart#187]
Since in parsing vsk file, there are marker sets with color information. I think Marker class constructor sholud  add  color item.

Marker(const std::string& _name, const Eigen::Vector3d& _offset, BodyNode* _bodyNode,  const Eigen::Vector4d& _color = Eigen::Vector4d::Identity(),  ConstraintType _type = NO);

**Comment by jslee02** [comment]
Created PR #561
