### ISSUE TITLE
Use FCL's broad phase

### ISSUE THREAD

**Issue by tobiaskunz** [dartsim/dart#20]
FCL includes functionality to smartly organize objects/link into a data structure such that not all pairs of them need to be checked for collision. We are currently not making use of that functionality and instead check all pairs for collision.

**Comment by scpeters** [comment]
I've been running some benchmark tests with a variable number of rigid bodies in a scene. Even without contact, the computational time scales superlinearly with the number of bodies for dart with FCL, while the other physics engines had roughly linear scaling.

**Comment by mxgrey** [comment]
Are the bodies primitives or meshes? Or are they a mixture?

**Comment by jslee02** [comment]
Boxes are all converted to meshes for FCL, and each box mesh has 12 triangles. So they are all meshes.

**Comment by mxgrey** [comment]
I worded my last comment poorly. I've revised it.

**Comment by jslee02** [comment]
It's related to #19, but unfortunately, FCL is not ready to use primitives for DART because of these issues (https://github.com/flexible-collision-library/fcl/issues/15, https://github.com/flexible-collision-library/fcl/issues/8).

I'm planning to make some changes for the issues and create pull requests.

**Comment by tobiaskunz** [comment]
While fixing #19 could improve performance in general, the issue raised by Steven has nothing to do with #19 and fixing #19 would not improve it. He did not compare absolute computation time, but the change in computation time with increasing number of bodies. Making use of FCL's broad phase could potentially improve this.

**Comment by jslee02** [comment]
@tobiaskunz is right. That's why I added "partially" but tobias's explanation is more correct.

**Comment by jslee02** [comment]
Addressed by #631
