### ISSUE TITLE
Minimize dependencies

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#242]
#### Core library
- [ ] boost (use C++11 features instead): regex, systems
- [ ] assimp (#453)

**Comment by mxgrey** [comment]
I could make flann an optional dependency by abstracting out the nearest neighbor search and offering a brute force searching algorithm as the default. I think for most modestly sized RRTs, brute force tends to be nearly as fast as flann, so flann could be made an optional dependency.

**Comment by jslee02** [comment]
Closing this issue because:
1. the planning component has been deprecated
1. Assimp is duplicated by #453
1. We don't drop boost dependency (probably until C++17)

Please reopen if anyone thinks this should be left open.
