### ISSUE TITLE
Managing generalized coordinate order

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#251]
A skeleton allows to get and set its generalized coordinates using vector. The problem is that the order of the generalized coordinates in the vector is not clear since skeleton reorders body nodes for internal use and it affects on the order of generalized coordinates. Also, it is not possible to specify the order under current API. 

 It would be good to have new API that can manage the order of generalized coordinates.

**Comment by mxgrey** [comment]
The new ``dart::dynamics::Group`` class allows arbitrary ordering of generalized coordinate indices.
