### ISSUE TITLE
Build error on Mac

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#282]
The dependency settings between namespaces are not completed in cmake configuration. This seems fine on Linux but not on Mac.

**Comment by scpeters** [comment]
I have observed linking errors with assimp in downstream projects (gazebo). Is that what you're referring to?

**Comment by jslee02** [comment]
Previously, DART generates single library file across all the namespaces. (More precisely, dart-core and dart) By #278, DART generates multiple library files for each namespaces and another single library file that has dependencies of the namespace-wise library files.

Building DART with the PR on linux is fine but somehow there are linking errors on Mac. I guess the dependency settings between the namespace-wise library files is causing the problem, but I'm not sure yet.

**Comment by scpeters** [comment]
Ok, it looks like that's the master branch. I was testing with dart 4.2.1, which seems ok

**Comment by jslee02** [comment]
Right, the change was merged to the master branch. DART 4.2.1 is still fine.
