### ISSUE TITLE
Add in gtest source to the build

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#312]
It is [not recommended by google](https://code.google.com/p/googletest/wiki/FAQ#Why_is_it_not_recommended_to_install_a_pre-compiled_copy_of_Goog) to install a pre-compiled copy of gtest, since it needs to use the same compiler flags as DART code.

It seems fine on Ubuntu since Ubuntu provides header only gtest package, but homebrew just doesn't even recommend to install gtest header from them (gtest is on their [blacklist](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/blacklist.rb#L44-L47)). We should add in gtest source like [Gazebo did](https://bitbucket.org/osrf/gazebo/src/d504d2050c0f0058a2606e836871bd80c44b6f45/test/gtest/?at=default).

Thanks @scpeters !

**Comment by scpeters** [comment]
I've added some discussion in https://github.com/dartsim/homebrew-dart/issues/3

**Comment by jslee02** [comment]
I changed this issue according to @scpeters 's recommendation.

**Comment by jslee02** [comment]
Fixed by #315
