### ISSUE TITLE
Cannot handle joint limit and joint friction together

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#317]
DART cannot handle joint constraints correctly when there exists joint friction and joint position limit at the same time. This is because the two constraints overwrite the constraint impulse rather than adding up.

**Comment by scpeters** [comment]
Thanks for fixing this and back-porting to 4.3. I've tested with gazebo and seen an improvement, though I had to relax the tolerances slightly (1e-4 to 1e-3).

* https://bitbucket.org/osrf/gazebo/commits/60614007ffa909f01399c3478707a85b7069bb61

Do you have any ideas why to tolerances were slightly violated? Constraint error correction?

**Comment by jslee02** [comment]
The main reason is that DART doesn't correct positional violation directly. Instead, DART uses artificial velocity with ERP (error reduction parameter) so that the position error is corrected by integrating the position with the velocity. If the ERP is 1.0 then position will be completely corrected, and if ERP is 0 then position will not be corrected. The default ERP is 0.01. If we increase this ERP then it might reduce the tolerance.

I picked the low value for the default ERP, which may not correct the error aggressively, because too much ERP would make the system instable.

To handle this more reliably, DART may need to solve LCP twice per simulation for velocity correction and position correction per every simulation step like ODE does unless we change the whole constraint handling framework to other than impulse-based method.
