### ISSUE TITLE
EulerJoint::AxisOrder enumeration is deceptive

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#321]
There are currently 4 enumerations for EulerJoint::AxisOrder, but only two of those enumerations appear to be supported in the code. Specifically, EulerJoint::updateLocalTransform(), EulerJoint::updateLocalJacobian(), and EulerJoint::updateLocalJacobianDeriv() only handle AO_XYZ and AO_ZYX in their code.

To me it seems like any axis orderings that are not supported should not be enumerated, or else the user will be left thinking that they can be used. If we extend support to those orderings in the future, I don't think there's any issue with adding them back into the enumeration at that time.

**Comment by jslee02** [comment]
Good point. Created [PR](#321) for this.
