### ISSUE TITLE
OSX build problem related to GLUT

### ISSUE THREAD

**Issue by scpeters** [dartsim/dart#329]
A user had trouble building gazebo ( https://github.com/osrf/homebrew-simulation/issues/36 ) due to a linking problem with GLUT when not building with `BUILD_CORE_ONLY=ON`. Are the GLUT libraries being exported as dependencies in the cmake config or pkg-config files? If they are not needed by downsteam users, we should just link the GLUT libraries with the apps and not the dart library.

As an aside, GLUT is only used by the `dart/gui` and `apps` code, which should only be built when `BUILD_CORE_ONLY=ON`. However, I see that [GLUT is always searched for](https://github.com/dartsim/dart/blob/master/CMakeLists.txt#L128-L140) (even when not `CORE_ONLY`), and it's library and header files are also always used.

**Comment by jslee02** [comment]
Fixed by #355
