### ISSUE TITLE
Should PlaneShape(normal, point) really be deprecated?

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#373]
I noticed that the constructor has been deprecated in favor of PlaneShape(normal, offset), but is it really necessary to deprecate it? I can imagine it being convenient for an end user to construct a PlaneShape using normal and point information, and I don't see why having the two alternative constructors would hurt anything.

**Comment by jslee02** [comment]
It's deprecated while changing the member variables from (normal, point(3d-vector)) to (normal, offset(scalar)) since point is redundant representation. I agree that `PlaneShape(normal, point)` is still convenient constructor. One minor concern is that we should provide `getPoint()` also or not.

**Comment by mxgrey** [comment]
I think that the point information is sort of lost once the plane is constructed, because there are infinite points that can be used to define a plane. I don't really see that function as being necessary.

**Comment by jslee02** [comment]
If the specific point information, which is provided the user, is fine to be lost, it looks good to have the constructor. I'll revert the deprecation.

**Comment by mxgrey** [comment]
Looks like this has been resolved.
