### ISSUE TITLE
Deprecated mark for clang

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#379]
[DART doesn't define deprecated mark for clang](https://github.com/dartsim/dart/blob/d6e38a79a4f798354f6435ae03b87d92f79eff12/dart/common/Deprecated.h#L46).

**Comment by mxgrey** [comment]
C++14 will introduce an ISO ``[[deprecated]]`` attribute tag, although I have no idea when that will be supported by GCC, Clang, and VS.

**Comment by mkoval** [comment]
Until then, it like [clang implements the same extension as GCC](http://clang.llvm.org/docs/LanguageExtensions.html#messages-on-deprecated-and-unavailable-attributes):

```c++
  #define DEPRECATED(version) __attribute__ ((deprecated))
```

**Comment by jslee02** [comment]
`[[deprecated]]` would be a simple and portable solution when all the three compilers support it.

Meanwhile, let's use the same extension as GCC. I'll create a pull request for this.
