### ISSUE TITLE
getRootBodyNode SEGFAULTs when out of range

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#388]
The [`getRootBodyNode` method](https://github.com/dartsim/dart/blob/memory_management/dart/dynamics/Skeleton.cpp#L380) doesn't do any bounds checking. It SEGFAULTs if you specify an index that is out of range. This is unexpected because the other getters use `getVectorObjectIfAvailable<T>` to return `nullptr` if the index is out of range.

**Comment by mxgrey** [comment]
The fix for this is ready to go; I just need to get it committed and push it to the repo.

**Comment by mxgrey** [comment]
This should now be fixed in #369

**Comment by mkoval** [comment]
Fixed in #390.
