### ISSUE TITLE
Signal when a MetaSkeleton's structure changes

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#448]
I'm writing some code that relies on the indexing of a `MetaSkeleton`. I'd like to invalidate my calculations if the structure of the skeleton changes; i.e. a `BodyNode` is added or removed, a `Joint` changes type, etc. I thought this was possible using `Signal`s, but I can't seem to find it.

Is this possible in the current API?

**Comment by mxgrey** [comment]
We can certainly put in a signal that gets triggered when indexing changes, but I don't believe that exists yet.

**Comment by mxgrey** [comment]
Now that we have the ``VersionCounter`` class, we could create a signal that gets triggered each time an object's version is incremented. Subscribing a slot to a Skeleton's version signal will then activate the slot each time the structural properties change. Alternatively, you can track a Skeleton's version number and do whatever handling is needed whenever you see a new version.

**Comment by mkoval** [comment]
> Alternatively, you can track a Skeleton's version number and do whatever handling is needed whenever you see a new version.

:+1: This is actually a better than a signal for my purposes. I am closing this issue.
