### ISSUE TITLE
Unit tests are failing on Windows

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#488]
It is observed that [some tests are failed on Windows](https://ci.appveyor.com/project/jslee02/dart/build/1589/job/6tfofah83u9mfaky#L1660). It seems the tests are failed because the uri parser is not compatible with windows style path like `c:\my\path\file.txt`. `c:` is regarded as a scheme.

**Comment by psigen** [comment]
I think this is related to the discussion in the PR:
https://github.com/dartsim/dart/pull/497#issuecomment-143279106

**Comment by mxgrey** [comment]
We probably should have had the discussion in here. At least they're linked together now.

**Comment by mkoval** [comment]
I think this was fixed in #497, #516, and #517.

@jslee02 or @mxgrey Can you close this now?

**Comment by jslee02** [comment]
Sure!
