### ISSUE TITLE
Joint has the default copy constructor

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#524]
I noticed that `Joint` does not `= delete` its copy constructor. I believe that all of the fields in `Joint` are copyable, so this means that the default copy (and, possibly, move) constructor is being implicitly defined by the compiler.

I suspect that is not intentional (and potentially dangerous!) because every `Joint` is supposed to be owned by it's child `BodyNode`.

**Comment by mxgrey** [comment]
It's definitely not intentional, and it's definitely dangerous. I'll submit a pull request to correct this later today.

**Comment by mxgrey** [comment]
It's also worth checking if this is an issue for BodyNode and Skeleton, since none of those should permit a copy construction.

**Comment by mkoval** [comment]
@mxgrey fixed this in #525. Thanks!

**Comment by mkoval** [comment]
`MultiDofJoint` and `ZeroDofJoint` still have copy constructors. :smile:

**Comment by mxgrey** [comment]
I'm pretty sure they'd technically be deleted by default since they inherit from a class whose copy constructor is deleted. Still, it would be good to be explicit about it.

**Comment by mkoval** [comment]
They're not - I discovered this because I'm using `libclang` to parse the DART source code and they're listed in the output. :laughing:

**Comment by mkoval** [comment]
`DegreeOfFreedom` also has a copy constructor.

**Comment by jslee02** [comment]
This seems to be resolved by #539.
