### ISSUE TITLE
MeshShape returns unscaled bounding box dimensions

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#546]
While investigating #545, @mklingen discovered that `mBoundingBoxDim` on `MeshShape` is not scaled by `mScale`. Instead, the scaling happens inside `computeVolume` and other methods that use `mBoundingBoxDim`. This means that the bounding box returned by `getBoundingBoxDim ` is incorrect on meshes with non-unit scale.

**Comment by mklingen** [comment]
@mkoval I believe this pr fixes it https://github.com/dartsim/dart/pull/547

**Comment by jslee02** [comment]
I believe so too. Please reopen if it's not.
