### ISSUE TITLE
NameManager::removeEntries calls a function that does not exist

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#554]
I got this error when calling `removeEntries` on `NameManager`:
```
dart/common/detail/NameManager.h:203:21: error: too many arguments to function
      call, expected single argument '_name', have 2 arguments
  removeName(_name, false);
  ~~~~~~~~~~        ^~~~~
```
I checked the source code and found that `removeName` does indeed have the function signature:
```c++
template <class T>
bool NameManager<T>::removeName(const std::string& _name)
```
I suspect that we never saw this before because `NameManager` is a template class and `removeEntries` is only instantiated when first referenced.

**Comment by jslee02** [comment]
I believe this is resolved by #564.
