### ISSUE TITLE
Some typo error in tutorial dominoes

### ISSUE THREAD

**Issue by JiaYeLi** [dartsim/dart#575]
http://dart.readthedocs.org/en/release-5.1/tutorials/dominoes/

in the Overview
Write a stable PD controller w/ gravity and coriolis compensation

I guess "w/" is with but I'm not sure

**Comment by mxgrey** [comment]
``w/`` is a common abbreviation for the word ``with``. It's not actually a typo, but it may be worth changing it to ``with`` explicitly if not everyone is familiar with that abbreviation.

**Comment by JiaYeLi** [comment]
Thank you, mxgrey.

I learned a new abbreviation.
I am sorry that I'm not a native speaker of English.

**Comment by mxgrey** [comment]
We'll definitely want DART and its documentation to be accessible to non-native English speakers, so I'm actually glad that you're not a native speaker of English; that will help us identify spots in the documentation that might be confusing or unclear for people who are not native speakers.

**Comment by jslee02** [comment]
I believe we can close this issue. Please re-open if not the case.
