### ISSUE TITLE
Add Texture to shape

### ISSUE THREAD

**Issue by costashatz** [dartsim/dart#594]
Hello,

I was wondering if it's possible to add texturing to a dart shape (e.g. BoxShape).

**Comment by mxgrey** [comment]
Textures are definitely possible with ``MeshShape``s. Are you using the native DART renderer, or are you using a wrapper, like Gazebo? I don't know offhand whether Gazebo supports the textures in DART's ``MeshShape`` class.

If you're using DART's native rendering, then I *think* the following approach should work (although I haven't tested it):

1. Create a textured box mesh in a 3D modelling program such as Blender
2. Load and add the mesh as a **visualization** shape for the BodyNode
3. Construct a BoxShape primitive and add it as a **collision** shape for the BodyNode

That should let you get the visual results that you want while still having good performance when it comes to collision detection.

**Comment by costashatz** [comment]
I think this is solved with #973 ...
