### ISSUE TITLE
getNumPluralAddoName method on Skeleton

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#615]
I noticed a method named `getNumPluralAddoName` method on `Skeleton`. I suspect this is being generated by a bug in one of the `DART_DYNAMICS_*_ADDON_*` macros.

**Comment by jslee02** [comment]
I believe this was fixed by https://github.com/dartsim/dart/commit/b575f521f9a83b117760ac60e23db4d847e4dfca.
