### ISSUE TITLE
Decrease minimum required bullet version from 2.82 to 2.81

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#625]
I set the minimum required bullet version 2.82 in the first place without any investigation. This prevents us from using DART with bullet on trusty (bullet version of trusty is 2.81) unless we install higher bullet version manually. [According to the change log](https://github.com/bulletphysics/bullet3/blob/master/docs/BulletQuickstart.pdf), it seems there is no change in collision module of bullet in 2.82 so we would be able to use 2.81 without any trouble.

**Comment by mkoval** [comment]
:+1: I also ran into this on Ubuntu 14.04

If 2.82 was chosen arbitrarily, is 2.81 any less arbitrary? Why not set the required version to just 2.0 unless we have a compelling reason to choose a later version?

**Comment by jslee02** [comment]
It's not a compelling reason but the reason is that the supporting Ubuntu distribution is trusty, which provides bullet 2.81.
