### ISSUE TITLE
Linking with Bullet fails on OS X El Capitan

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#657]
I am attempting to build DART on OS X 10.11 (El Capitan). Compilation fails with this error:
```
Undefined symbols for architecture x86_64:
  "btStaticPlaneShape::btStaticPlaneShape(btVector3 const&, float)", referenced from:
      dart::collision::BulletCollisionNode::BulletCollisionNode(dart::dynamics::BodyNode*) in BulletCollisionNode.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have Bullet 2.83.6 installed from Homebrew.

**Comment by jslee02** [comment]
Guess: It seems like this is related to [this answer](http://stackoverflow.com/a/25080111). DART uses **libc++**, and probably the binary version of Bullet in Homebrew uses **libstdc++**?

I could compile DART with Bullet 2.83 compiled myself with no problem.
