### ISSUE TITLE
Automatically updating CollisionGroups when ShapeNodes are added/removed

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#664]
1. Currently a `CollisionGroup` will only pay attention to the `ShapeNode`s on a `BodyNode` or `Skeleton` that are present at the moment that they are handed over. It would be good if they could update automatically whenever the `ShapeNode`s are altered in some way. We could possibly do this with a wrapper class or build the functionality into `CollisionGroup` itself.
2. `CollisionGroup` currently does not know when a `ShapeFrame` it refers to gets destroyed. This can leave the `CollisionGroup` in an undefined state and lead to undesirable behavior.

**Comment by jslee02** [comment]
I believe this is resolved by #1112
