### ISSUE TITLE
enableSelfCollision has a misleading argument

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#702]
`enableSelfCollision` takes a `_enableAdjacentBodyCheck` boolean argument. This leads to the unintuitive behavior that this line actually *enables* self-collision checking:
```c++
skeleton->enableSelfCollision(false);
```

It also leads to a strange asymmetry, where there is no way to change the value of `isEnabledAdjacentBodyCheck` without also enabling self-collision detection. I suggest deprecating `enableSelfCollision` and replacing it with two separate functions: one for enabling/disabling self collision checks and one for enabling/disabling adjacent body checks.

**Comment by jslee02** [comment]
Resolved by #718
