### ISSUE TITLE
Discussion: namespace vs prefix

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#728]
Since [#652](https://github.com/dartsim/dart/pull/652), DART has been composed as the core library `dart` and several component libraries like `dart-optimizer-nlopt`, and the component libraries get compiled only when the required dependencies are installed. We then introduced `dart::gui::osg` namespace for OpenSceneGraph dependent library rather than using prefix like `dart::gui::OsgViewer`. However, we still use prefixes for other component classes like `NloptSolver` and `IpoptSolver`. I think we should follow one rule for consistency, but not sure which one is preferred way.

After Googling, I learned that using namespaces is the C++ way while using prefixes is the C way, and I'm inclined to using namespaces because of this reason.

Downsides of using namespace I can imagine would be (1) that it would require more typing for `::` (e.g., `NloptSolver` vs `nlopt::Solver`) and (2) that it could cause namespace conflict with the dependency namespace (e.g., `dart::collision::fcl` of DART and `fcl` of FCL). (2) can be resolved by using the global namespace specifier like `::fcl` for FCL namespace, though.

Here are some examples of current, namespace, and prefix cases.

**current**

``` cpp
dart::collision::FCLCollisionDetector
dart::collision::BulletCollisionDetector
dart::collision::DARTCollisionDetector

dart::optimizer::NloptSolver
dart::optimizer::IpoptSolver

dart::gui::GlutWindow
dart::gui::osg::[~]
```

**prefix**

``` cpp
dart::collision::FCLCollisionDetector
dart::collision::BulletCollisionDetector
dart::collision::DARTCollisionDetector

dart::optimizer::NloptSolver
dart::optimizer::IpoptSolver

dart::gui::GlutWindow
dart::gui::GlfwWindow
dart::gui::Osg[~]
```

**namespace**

``` cpp
dart::collision::fcl::CollisionDetector
dart::collision::bullet::CollisionDetector
dart::collision::dart::CollisionDetector // or something like dart::collision::builtin::CollisionDetector since dart::collision::dart would be ambiguous

dart::optimizer::nlopt::Solver
dart::optimizer::ipopt::Solver

dart::gui::glut::Window
dart::gui::glfw::Window
dart::gui::osg::[~]
```

**Comment by mxgrey** [comment]
I think we can close this, since we've settled pretty strongly on using namespaces instead of prefixes.
