### ISSUE TITLE
Ways to load and parse ASF/AMC motion data

### ISSUE THREAD

**Issue by lucaskotw** [dartsim/dart#730]
Is there an elegant way to load [ASF/AMC motion data](http://research.cs.wisc.edu/graphics/Courses/cs-838-1999/Jeff/ASF-AMC.html) and apply them to a skeleton? I just simply parse the data and assign the kinematic data. It will be great if there's a built-in method.

If there has no handy ways to read them, could I propose a way to parse it? ASF/AMC format seem a neat way to record the motion capture data.

**Comment by jslee02** [comment]
:+1: It sounds good to me. I don't know about the format, but it looks like VSK file. VskParser and other parser classes would be helpful when you implement the parser. Just let us know if you need any help.

**Comment by lucaskotw** [comment]
Thanks! I'll try to implement first and post related issues.

**Comment by jslee02** [comment]
Closing this issue for now. Feel free to reopen when there is an update :)
