### ISSUE TITLE
Secret upper limit for time step when using SimWindow

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#735]
It turns out that the `SimWindow` class secretly does not support simulation time steps which exceed `1.0/30.0`. This is because of [this line](https://github.com/dartsim/dart/blob/d6e2d3dedad90fb4ac4cc0ac6c878f4657943d5c/dart/gui/SimWindow.cpp#L120). The variable `mDisplayTimeout` is equal to `1000.0/30.0` (it gets set [here](https://github.com/dartsim/dart/blob/d6e2d3dedad90fb4ac4cc0ac6c878f4657943d5c/dart/gui/GlutWindow.cpp#L63)) so then if `mWorld->getTimeStep()` is greater than `1.0/30.0`, then `mDisplayTimeout/(mWorld->getTimeStep()*1000)` will come up as `0`. This instructs the window to run `0` simulation iterations per refresh.

One option would be to change the line to

```
int numIter = ceil(static_cast<double>(mDisplayTimeout) / (mWorld->getTimeStep() * 1000.0));
```

This would guarantee that a simulation timestep is always called at least once per refresh. I think a more satisfying solution would be to just have a variable in SimWindow that lets the user determine how many simulation iterations are run per refresh.

**Comment by jslee02** [comment]
Closing as the glut renderer is deprecated
