### ISSUE TITLE
Aspect-related functions are missing in Doxygen

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#737]
I noticed that all of the `Aspect`-related functions are missing from the DART 6 Doxygen pages. This is a serious usability problem: even non-template functions like `getCollisionAddon` are missing, so it's not obvious how to change the properties of a `ShapeFrame`.

Hopefully fixing this is just a matter of tweaking some settings in the `Doxyfile`.

**Comment by jslee02** [comment]
I believe this is [addressed](http://dartsim.github.io/dart/d9/d52/classdart_1_1dynamics_1_1ShapeFrame.html#adba7f396c571dc081bacba4ddf2ec0ad) by #768.
