### ISSUE TITLE
Missing tag for the 6.0.1 release

### ISSUE THREAD

**Issue by mkoval** [dartsim/dart#754]
There are tags for all of patch version releases except for 6.0.1. I think this may have been a simple oversight, e.g. forgot to push the tag after creating it.

I noticed this when trying to checkout `v6.0.1` in #752.

**Comment by jslee02** [comment]
Actually, we haven't released yet pending #741.

**Comment by mkoval** [comment]
I have `v6.0.1` installed from the DART PPA on Ubuntu 14.04, so it's definitely released:
```
$ dpkg-query --show libdart6
libdart6    6.0.1.ppa4~trusty
```

**Comment by jslee02** [comment]
I messed up the procedure of releasing 6.0.1. `6.0.1.ppa4~trusty` was for testing. I should've used different package name like `libdart6-prerelease`.

Anyways, I will finish the procedure in this order:

1. Merge #741.
2. (probably) Upload `libdart6-prerelease` for testing.
3. Tag v6.0.1.

**Comment by mkoval** [comment]
I don't think that is a good idea. It's not possible to re-release a version of a Debian package because it will cause everyone who previously `apt-get update` to get a hash mismatch. It also means that some people (like me) will have a version `6.0.1` installed that does not match the `v6.0.1` tag.

Instead, I suggest that you tag the version of the code that you did release as `v6.0.1` and change the release in #741 to 6.0.2. 😓

**Comment by jslee02** [comment]
> Instead, I suggest that you tag the version of the code that you did release as v6.0.1 and change the release in #741 to 6.0.2.

That sounds good to me.

**Comment by jslee02** [comment]
[v6.0.1](https://github.com/dartsim/dart/releases/tag/v6.0.1) is created.
