### ISSUE TITLE
Rendering - white lines for non-osg display with nvidia driver

### ISSUE THREAD

**Issue by fredowski** [dartsim/dart#804]
Hi, 

i compiled the current DART git version "last commit: Update Control - 19.10.2016" and tried some of the examples. I noticed that there is a difference in the rendering result between the osg examples and the non-osg examples. I think there is a difference in the OpenGL configuration. My system setup is debian jessie NVidia GTX 1080 with native NVidia Driver version 367.48. 

Here is the non-osg atlasSimbicon on NVidia GTX1080 with white lines:

![non-osg-whitelines](https://cloud.githubusercontent.com/assets/1280457/19650679/6c7fadc0-9a0a-11e6-9e1c-caa1aefabaa0.JPG)

Here is osgAtlassimbicon on GTX1080  with no white lines:
![osg-no-whitelines](https://cloud.githubusercontent.com/assets/1280457/19650729/92adf3bc-9a0a-11e6-8267-adb4484a5294.JPG)

Jeongseok figured out that the white lines are not visible with a Intel Integrated Graphics Controller:

![intel-no-white-lines](https://cloud.githubusercontent.com/assets/1280457/19650816/e3e3fac4-9a0a-11e6-81de-c40e4e1830a3.png)

**Comment by fredowski** [comment]
Hi Jeongseok,

i think I found the problem regarding the strange white lines. With pullrequest #805 this should be fixed. With the change there are no white lines anymore.

Regards

Friedrich

**Comment by jslee02** [comment]
Awesome! Resolved by #805.
