### ISSUE TITLE
Consider renaming namespace `utils` to `io`

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#815]
`io` (stands for Input/Output) would be a more relevant name with the code that `utils` contains while `utils` is too general.

**Comment by mkoval** [comment]
I generally like this idea. If there are parts of `utils` that are not related to I/O, perhaps we could move them to `common`? I don't see a strong distinction between `utils` and `common` as it stands.

**Comment by jslee02** [comment]
> If there are parts of utils that are not related to I/O, perhaps we could move them to common?

I think so. I 

>  I don't see a strong distinction between utils and common as it stands.

They were originally one directory as utils. I seperated out common from utils in the process of arranging the dependencies between the subdirectories (we didn't even have namespaces at that time). After that, it turned out utils only contains IO related functionalities.

**Comment by psigen** [comment]
This seems like a reasonable refactor to me.  I think it's a good idea to have an `io` namespace in general.
