### ISSUE TITLE
How to start simulation

### ISSUE THREAD

**Issue by tlsdba** [dartsim/dart#831]
Hi,
I have compiled dart5.1.4 by using VS2015, but when I run the samples like Dominoes, I pressed 'spacebar' or 'p', the simulation can't work. Can you help me? 
Thanks

**Comment by jslee02** [comment]
Could you please elaborate what do you mean by "can't work"?

**Comment by jslee02** [comment]
Closing due to lack of a response. Please re-open if you have further trouble.
