### ISSUE TITLE
Contact solving wrongly

### ISSUE THREAD

**Issue by tianyang9310** [dartsim/dart#841]
I came across a bug where DART (release-5.1) doesn't solve contact correctly. Please refer to my branch (https://github.com/tianyang9310/dart/tree/DART_ODE_BUG).

Please run CntctLrnin in apps directory. In MyWindow.cpp file, if external force is added as 
`Extforce(0)=1.2e1`
then the cube will move, while if external force is 
``` 
extForce(0) = 1.2e1*std::cos(45.0/180.0*DART_PI);  
extForce(2) = 1.2e1*std::sin(45.0/180.0*DART_PI);
```
then the cube is not going to move.

**Comment by jslee02** [comment]
We've discussed on this through email. In a nutshell, this was because the friction cone model of ODE is not friction direction invariant rather than a bug of DART.
