### ISSUE TITLE
Need more explanation on setting friction coefficient

### ISSUE THREAD

**Issue by ljklonepiece** [dartsim/dart#848]
for function 
`
void dart::dynamics::BodyNode::setFrictionCoeff	(	double 	_coeff	)	
`
it sets friction coefficient on one object, but normally friction coefficient is defined between two surfaces.
Shall I interpret this function to set the friction coefficient between this object and any objects? 
but for example A and B are in contact,
`body_A->setFrictionCoeff(0.5)`
`body_B->setFrictionCoeff(1.0)`

What should be the resulting friction coeff between A and B?

**Comment by jslee02** [comment]
[DART uses the minimum value when they are different](https://github.com/dartsim/dart/blob/master/dart/constraint/ContactConstraint.cpp#L97). Also, I agree that this should be documented (at least) on `setFrictionCoeff()`, and will do this soon.

**Comment by mxgrey** [comment]
It makes sense that some users may want to define friction properties pairwise, since that is more technically accurate.

I wonder if we could implement a ``FrictionFilter`` similar to the ``CollisionFilter`` which might look something like

```
using FrictionFilter = std::function<double(const BodyNode* bn1, const BodyNode* bn2)>;
```

Then if ``FrictionFilter`` is not set, we fall back on the current method.

**Comment by jslee02** [comment]
I like the idea! I would prefer `FrictionFunction` though.

**Comment by mxgrey** [comment]
That's definitely a better name. Using "filter" was mostly to relate it to the existing ``CollisionFilter``.

**Comment by jslee02** [comment]
Sure, I presumed so. :smile:

**Comment by jslee02** [comment]
Closing due to lack of a response. Please re-open if you have further trouble.
