### ISSUE TITLE
Performance test: dart::math::expAngular() vs Eigen::AngleAxis()

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#88]
DART has own exponential mapping function, dart::math::expAngular(), and Eigen also has Eigen::AngleAxis() which has same functionality. We may need to know which one performs better.

**Comment by mxgrey** [comment]
The speed test I wrote could come in handy here. We could use the same speed test on two branches, one branch using dart::math:expAngular() and the other branch using Eigen::AngleAxisd(). However, the speed test would not check for numerical accuracy; I don't know if that's a concern or not.

**Comment by mxgrey** [comment]
It turns out that Eigen::AngleAxisd is in fact faster and more robust than DART's existing implementation. Pull request #334 replaces the existing implementation with Eigen::AngleAxisd.

**Comment by jslee02** [comment]
I believe this is resolved.
