### ISSUE TITLE
URDF joint friction not read into models

### ISSUE THREAD

**Issue by costashatz** [dartsim/dart#890]
When loading URDF files, the dynamics property "friction" of the joints seems to be ignored. The viscous friction (damping coefficient) is properly read and set, but the coulomb friction not. I tried several URDFs and it's always the same.

```xml
     <joint name="joint_name" type="revolute">
            <parent link="parent_link"/>
            <child link="child_link"/>
            <dynamics damping="this is ok" friction="THIS IS IGNORED" />
            .....
        </joint>
```

I am using the latest master branch..

Thanks...

**Comment by jslee02** [comment]
Thanks for this report. I believe this should be resolved by #891.
