### ISSUE TITLE
Provide setRelativeTransform() function for WeldJointConstraint

### ISSUE THREAD

**Issue by mxgrey** [dartsim/dart#903]
Per the discussion [here](https://bitbucket.org/osrf/gazebo/pull-requests/2756/dart-kinematic-loops/activity#comment-42226916) it would likely be a useful feature.

**Comment by pchorak** [comment]
Gazebo [issue #2339](https://bitbucket.org/osrf/gazebo/issues/2339) could be solved with this feature.

**Comment by jslee02** [comment]
Resolved by #910
