### ISSUE TITLE
Remove planning component in DART 7

### ISSUE THREAD

**Issue by jslee02** [dartsim/dart#920]
~~`planning` component will be moved to a separate repository something like `dartsim/dart-planning` as a legacy code repository.~~

Edit: We will remove the `planning` component in the new major release. Please consider to fork it off if anyone wants to use it and maintain it.

**Comment by mxgrey** [comment]
Frankly, I wouldn't mind just deleting it if no one is using it. Moving it to another repository without a dedicated maintainer is essentially a death sentence for it anyway.

If anyone feels sentimental about it (or is actually still using it) and they want to maintain it, then they can fork it off themselves and look after it.

**Comment by psigen** [comment]
One reason to branch it might be to allow people who are implementing their
own planners to find it as a reference.

Even if it is deprecated, it might still have use in illustrating how one
might architect a planner. If it's a bad example of that as well, then we
should just delete it.

**Comment by jslee02** [comment]
Moving planning component to another repository isn't that tedious work. So let's do it as the consensus here. I believe we all at least agree to move code that isn't maintained by us out from this repository.
