### ISSUE TITLE
Build Ubuntu artful debs in ppa

### ISSUE THREAD

**Issue by scpeters** [dartsim/dart#960]
I don't see any debs for Ubuntu Artful in the PPA:

* https://launchpad.net/~dartsim/+archive/ubuntu/ppa

Is it possible to build some?

**Comment by jslee02** [comment]
There is `dart6 - 6.3.0.ppa2~artful`! :sweat_smile:

**Comment by scpeters** [comment]
wow, I don't know what I was thinking

I saw an error message related to the PPA in this job:

* https://build.osrfoundation.org/view/main/view/gazebo/job/gazebo-ci-default-artful-amd64-gpu-none/1/console

but I didn't look closely enough at your PPA

Sorry for the bad report

**Comment by jslee02** [comment]
No worries. It's a long log. :scream:
